### ISSUE TITLE
输入问题

### ISSUE THREAD

**Issue by lixiaohaao** [MekAkUActOR/BAG_MulVAL#1]
我曾经在bag_mulval的网页上输入了对单目标靶机的扫描报告，并且转成了.p文件，但是语法一直提示我文件类型错误或者语法错误。我想请问一下mulval是不支持对单目标的攻击图建立吗？

**Comment by MekAkUActOR** [comment]
你可以把你的.P文件（datalog文件）发给我看看。另外我的网页上的攻击图分析程序现在有点bug，我之前修好了但没更新。刘浩文 mekakuactor.cn上海交通大学 网络空间安全学院------------------ 原始邮件 ------------------From: lixiaohaao  ***@***.***>发送时间: 06/22/2021, 08:06To: MekAkUActOR/BAG_MulVAL ***@***.***>抄送: Subscribed ***@***.***>Subject: Reply:[MekAkUActOR/BAG_MulVAL] 输入问题 (#1)
我曾经在bag_mulval的网页上输入了对单目标靶机的扫描报告，并且转成了.p文件，但是语法一直提示我文件类型错误或者语法错误。我想请问一下mulval是不支持对单目标的攻击图建立吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MekAkUActOR/BAG_MulVAL/issues/1",
"url": "https://github.com/MekAkUActOR/BAG_MulVAL/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lixiaohaao** [comment]
我对电脑上不同的靶机扫描的报告也在这边，我通过邮箱发给你，不知道你能不能收到。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MekAkUActOR/BAG_MulVAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MekAkUActOR/BAG_MulVAL] 输入问题 (#1)





 你可以把你的.P文件（datalog文件）发给我看看。另外我的网页上的攻击图分析程序现在有点bug，我之前修好了但没更新。刘浩文&nbsp;mekakuactor.cn上海交通大学&nbsp;网络空间安全学院------------------ 原始邮件 ------------------From: lixiaohaao  ***@***.***&gt;发送时间: 06/22/2021, 08:06To: MekAkUActOR/BAG_MulVAL ***@***.***&gt;抄送: Subscribed ***@***.***&gt;Subject: Reply:[MekAkUActOR/BAG_MulVAL] 输入问题 (#1)
 我曾经在bag_mulval的网页上输入了对单目标靶机的扫描报告，并且转成了.p文件，但是语法一直提示我文件类型错误或者语法错误。我想请问一下mulval是不支持对单目标的攻击图建立吗？
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 [
 {
 ***@***.***": "http://schema.org",
 ***@***.***": "EmailMessage",
 "potentialAction": {
 ***@***.***": "ViewAction",
 "target": "https://github.com/MekAkUActOR/BAG_MulVAL/issues/1",
 "url": "https://github.com/MekAkUActOR/BAG_MulVAL/issues/1",
 "name": "View Issue"
 },
 "description": "View this Issue on GitHub",
 "publisher": {
 ***@***.***": "Organization",
 "name": "GitHub",
 "url": "https://github.com"
 }
 }
 ]

**Comment by lixiaohaao** [comment]
我把我利用Nusses的扫描报告转化的.p文件发送给你。不知道能不能收到。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MekAkUActOR/BAG_MulVAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MekAkUActOR/BAG_MulVAL] 输入问题 (#1)





 你可以把你的.P文件（datalog文件）发给我看看。另外我的网页上的攻击图分析程序现在有点bug，我之前修好了但没更新。刘浩文&nbsp;mekakuactor.cn上海交通大学&nbsp;网络空间安全学院------------------ 原始邮件 ------------------From: lixiaohaao  ***@***.***&gt;发送时间: 06/22/2021, 08:06To: MekAkUActOR/BAG_MulVAL ***@***.***&gt;抄送: Subscribed ***@***.***&gt;Subject: Reply:[MekAkUActOR/BAG_MulVAL] 输入问题 (#1)
 我曾经在bag_mulval的网页上输入了对单目标靶机的扫描报告，并且转成了.p文件，但是语法一直提示我文件类型错误或者语法错误。我想请问一下mulval是不支持对单目标的攻击图建立吗？
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 [
 {
 ***@***.***": "http://schema.org",
 ***@***.***": "EmailMessage",
 "potentialAction": {
 ***@***.***": "ViewAction",
 "target": "https://github.com/MekAkUActOR/BAG_MulVAL/issues/1",
 "url": "https://github.com/MekAkUActOR/BAG_MulVAL/issues/1",
 "name": "View Issue"
 },
 "description": "View this Issue on GitHub",
 "publisher": {
 ***@***.***": "Organization",
 "name": "GitHub",
 "url": "https://github.com"
 }
 }
 ]

**Comment by lixiaohaao** [comment]
[nusses2.zip](https://github.com/MekAkUActOR/BAG_MulVAL/files/6706468/nusses2.zip)

**Comment by killua2kid** [comment]
你好，我和你是一样的问题，请问你解决了吗？

**Comment by killua2kid** [comment]
> 我曾经在bag_mulval的网页上输入了对单目标靶机的扫描报告，并且转成了.p文件，但是语法一直提示我文件类型错误或者语法错误。我想请问一下mulval是不支持对单目标的攻击图建立吗？

请问这个问题你现在解决了吗？如果解决了可以分享一下解决方案吗？

**Comment by MekAkUActOR** [comment]
Sorry for the late response. You can refer to https://github.com/JianmingGuo/Sicsp_ICS, which is the main project. And I believe MulVAL provides such tool to transfer .nessus to .p, but before that you should configure a vuln database.
